version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: php_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - DB_DRIVER=pdo_mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=ddd_db
      - DB_USER=admin
      - DB_PASSWORD=admin
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ddd_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
